# Generated by Django 4.0.5 on 2022-09-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_Cast',
            new_name='MovieCast',
        ),
        migrations.RenameModel(
            old_name='Movie_Run',
            new_name='MovieRun',
        ),
    ]
